Repository heritagefund/funding-frontend, pull requests merged in 2020-07, with the labels that each got.

#418 Added missing timestamp columns via a migration script
  db/migrate/20200724132622_add_missing_timestamp_columns.rb
  db/schema.rb
Labels: bug, ruby

#419 Added missing position column to people table via a migration script
  db/migrate/20200724135222_add_missing_position_column.rb
  db/schema.rb
Labels: bug

#411 Added dependabot.yml configuration file
  dependabot.yml
Labels: dependencies, enhancement

#420 Abstracted content from alternative finance start page
  app/views/funding_application/hef_loan/start/show.html.erb
  config/application.rb
  config/locales/funding_application/hef_loan/start/en.yml
  config/locales/hef_loan_start.yml
Labels: enhancement, ruby

#423 Added validation to alternative finance supporting documents page
  app/controllers/funding_application/hef_loan/supporting_documents_controller.rb
  app/views/funding_application/hef_loan/supporting_documents/show.html.erb
Labels: enhancement, ruby

#422 added validation for loan amount
  app/models/gp_hef_loan.rb
  config/locales/en.yml
  db/migrate/20200619081912_create_people.rb
  db/migrate/20200619082127_create_people_addresses.rb
Labels: enhancement, ruby

#425 Added functionality to strip commas from currency inputs
  app/models/gp_hef_loan.rb
  config/locales/en.yml
Labels: enhancement, ruby

#427 Feature/validate repayment length
  app/models/gp_hef_loan.rb
  config/locales/en.yml
  db/migrate/20200728071129_change_gp_hef_loans_amend_time_to_repay_loan.rb
  db/schema.rb
Labels: enhancement, ruby

#426 Added summary of errors markup to alternative finance form view
  app/views/funding_application/hef_loan/form/partials/_summary_of_errors.html.erb
  app/views/funding_application/hef_loan/form/show.html.erb
Labels: enhancement, ruby

#428 Updated Rails from 6.0.3.1 to 6.0.3.2
  Gemfile
  Gemfile.lock
Labels: dependencies

#429 Removed form_helper.rb and reference
  app/controllers/funding_application/hef_loan/form_controller.rb
  app/helpers/funding_application/hef_loan/form_helper.rb
Labels: invalid, ruby

#430 Changed log levels and logged out response bodies
  app/jobs/application_to_sharepoint_job.rb
Labels: ruby, tech debt

#432 Added tests for application_to_sharepoint_job.rb
  app/jobs/application_to_sharepoint_job.rb
  config/environments/test.rb
  spec/factories/funding_applications.rb
  spec/factories/gp_hef_loans.rb
  spec/jobs/application_to_sharepoint_job_spec.rb
  spec/rails_helper.rb
  spec/support/fake_objects.rb
Labels: ruby, tech debt, tests

#433 Added Welsh translation for alt finance start page
  config/locales/cy.yml
  config/locales/funding_application/hef_loan/start/cy.yml
Labels: enhancement

#434 Abstracted content from alternative finance supporting docs page
  app/views/funding_application/hef_loan/supporting_documents/show.html.erb
  config/locales/funding_application/hef_loan/supporting_documents/en.yml
Labels: enhancement, ruby

#435 Added Welsh translation for alt finance supporting docs page
  app/controllers/funding_application/hef_loan/supporting_documents_controller.rb
  config/locales/cy.yml
  config/locales/funding_application/hef_loan/supporting_documents/cy.yml
  config/locales/funding_application/hef_loan/supporting_documents/en.yml
Labels: enhancement, ruby

#436 Abstracted content from alt finance application submitted page
  app/views/funding_application/hef_loan/application_submitted/show.html.erb
  config/locales/funding_application/hef_loan/application_submitted/en.yml
  config/locales/hef_loan_application_submitted.yml
Labels: enhancement, ruby

#437 Minor content change to alt finance supporting docs page
  config/locales/funding_application/hef_loan/supporting_documents/cy.yml
  config/locales/funding_application/hef_loan/supporting_documents/en.yml
Labels: enhancement, ruby

#438 Added Welsh translation for alt finance application submitted page
  app/controllers/funding_application/hef_loan/application_submitted_controller.rb
  config/locales/funding_application/hef_loan/application_submitted/cy.yml
Labels: enhancement, ruby

#431 Added .cfignore file
  .cfignore
Labels: enhancement
