Repository heritagefund/funding-frontend, pull requests merged in 2020-02, with the labels that each got.

#262 Reinstated @has_file_upload instance variable
  app/controllers/project/project_cash_contribution_controller.rb
  app/controllers/project/project_support_evidence_controller.rb
Labels: bug

#261 Initial iteration of JavaScript refactoring
  app/javascript/error-handling/index.js
  app/javascript/packs/application.js
  app/views/project/project_capital_works/show.html.erb
  app/views/project/project_capital_works/show.js.erb
  app/views/project/project_cash_contribution/show.js.erb
  app/views/project/project_support_evidence/show.js.erb
Labels: tech debt

#264 Implemented organisation mission fix and tidied controller
  app/controllers/organisation/mission_controller.rb
  app/views/organisation/mission/show.html.erb
Labels: bug

#265 Included initial RSpec configuration
  .rspec
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: tech debt

#268 Added integration tests for organisation mission_controller
  Gemfile
  Gemfile.lock
  spec/controllers/organisation/mission_controller_spec.rb
  spec/factories/organisations.rb
  spec/factories/users.rb
  spec/rails_helper.rb
  spec/support/controller_macros.rb
  spec/support/factory_bot.rb
Labels: tech debt

#270 Fixes for org_type and application submitted bugs
  app/controllers/concerns/project_context.rb
  app/models/project.rb
  test/fixtures/organisations.yml
  test/models/project_test.rb
Labels: bug

#271 Added integration tests for organisation type controller
  spec/controllers/organisation/type_controller_spec.rb
Labels: tech debt

#272 Added integration tests for organisation numbers controller
  spec/controllers/organisation/numbers_controller_spec.rb
Labels: tech debt

#273 Added integration tests for organisation summary controller
  spec/controllers/organisation/summary_controller_spec.rb
Labels: tech debt

#284 Refactoring of legal signatories
  app/controllers/organisation/signatories_controller.rb
  app/models/legal_signatory.rb
  app/models/organisation.rb
  app/views/organisation/signatories/show.html.erb
Labels: tech debt

#287 Added integration tests for legal signatories controller
  spec/controllers/organisation/signatories_controller_spec.rb
  spec/factories/legal_signatories.rb
Labels: tech debt

#286 add acceptance tests for organisation creation
  spec/features/address_lookup_spec.rb
  spec/features/helpers.rb
  spec/features/organisation_spec.rb
  spec/rails_helper.rb
Labels: tech debt

#291 Added organisation about controller integration tests
  app/controllers/organisation/about_controller.rb
  spec/controllers/organisation/about_controller_spec.rb
Labels: tech debt

#292 Updated README.md with generation how-to
  README.md
Labels: documentation

#293 Added a single unhappy path feature test for organisation creation
  spec/features/organisation_spec.rb
Labels: tech debt

#294 Added extra Postgres environment variables to GitHub Action
  .github/workflows/continuous-integration-workflow.yml
Labels: bug

#296 Amended log line to stop error being thrown
  app/controllers/concerns/postcode_lookup.rb
Labels: bug

#297 Added initial acceptance test for application submission
  .github/workflows/continuous-integration-workflow.yml
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/health_controller_spec.rb
  spec/controllers/released_form_controller_spec.rb
  spec/factories/organisations.rb
  spec/factories/project_costs.rb
  spec/factories/projects.rb
  spec/factories/users.rb
  spec/features/about_you_spec.rb
  spec/features/project_spec.rb
  spec/helpers/postcode_helper_spec.rb
  spec/jobs/application_to_salesforce_job_spec.rb
  spec/models/project_spec.rb
  spec/support/fake_salesforce_webhook.rb
  test/application_system_test_case.rb
  test/controllers/.keep
  test/controllers/dashboard_controller_test.rb
  test/controllers/health_controller_test.rb
  test/controllers/released_form_controller_test.rb
  test/controllers/support_controller_test.rb
  test/factories/cash_contributions.rb
  test/factories/project_costs.rb
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/fixtures/legal_signatories.yml
  test/fixtures/organisations.yml
  test/fixtures/permission_to_start.json
  test/fixtures/projects.yml
  test/fixtures/released_forms.yml
  test/fixtures/users.yml
  test/helpers/.keep
  test/helpers/postcode_helper_test.rb
  test/integration/.keep
  test/jobs/application_attachments_to_salesforce_job_test.rb
  test/jobs/application_to_salesforce_job_test.rb
  test/mailers/.keep
  test/models/.keep
  test/models/cash_contribution_test.rb
  test/models/legal_signatory_test.rb
  test/models/organisation_test.rb
  test/models/project_cost_test.rb
  test/models/project_test.rb
  test/models/released_form_test.rb
  test/models/user_test.rb
  test/models/volunteer_test.rb
  test/support/fake_salesforce_webhook.rb
  test/system/.keep
  test/test_helper.rb
Labels: ruby, tech debt

#300 Addition of application payload log
  app/jobs/application_to_salesforce_job.rb
Labels: ruby

#298 Refactoring of AJAX error handling
  app/javascript/error-handling/index.js
  app/views/project/project_capital_works/show.js.erb
  app/views/project/project_cash_contribution/show.html.erb
  app/views/project/project_cash_contribution/show.js.erb
  app/views/project/project_support_evidence/show.html.erb
  app/views/project/project_support_evidence/show.js.erb
Labels: tech debt

#295 Added an ActionView Component for Save and continue button
  Gemfile
  Gemfile.lock
  app/components/button_component.html.erb
  app/components/button_component.rb
  app/views/devise/sessions/new.html.erb
  config/application.rb
  config/environments/development.rb
  config/locales/en.yml
  spec/components/button_component_spec.rb
  spec/components/previews/button_component_preview.rb
  spec/rails_helper.rb
Labels: enhancement, tech debt

#302 Added integration tests for project title controller
  app/controllers/project/project_title_controller.rb
  app/controllers/project/title_controller.rb
  app/views/project/title/show.html.erb
  config/routes.rb
  spec/controllers/project/title_controller_spec.rb
Labels: ruby, tech debt

#305 Fixed incorrect links on check your answers page
  app/views/project/project_check_answers/_best_placed.html.erb
  app/views/project/project_check_answers/_involvement.html.erb
Labels: bug

#303 Added integration tests for project description
  app/controllers/project/description_controller.rb
  app/controllers/project/project_description_controller.rb
  app/controllers/project/project_location_controller.rb
  app/models/project.rb
  app/views/project/description/show.html.erb
  app/views/project/project_description/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/description_controller_spec.rb
Labels: ruby, tech debt

#304 Added integration tests for project best_placed_description
  app/controllers/project/best_placed_controller.rb
  app/controllers/project/project_best_placed_controller.rb
  app/models/project.rb
  app/views/project/best_placed/show.html.erb
  app/views/project/project_best_placed/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/best_placed_controller_spec.rb
Labels: ruby, tech debt

#306 Project difference integration test
  app/controllers/project/difference_controller.rb
  app/controllers/project/project_difference_controller.rb
  app/models/project.rb
  app/views/project/difference/show.html.erb
  app/views/project/project_difference/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/difference_controller_spec.rb
Labels: ruby, tech debt

#307 Added integration test for project matter controller
  app/controllers/project/matter_controller.rb
  app/controllers/project/project_matters_controller.rb
  app/models/project.rb
  app/views/project/matter/show.html.erb
  app/views/project/project_matters/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/matter_controller_spec.rb
Labels: ruby, tech debt

#309 Added project heritage controller integration tests
  app/controllers/project/heritage_controller.rb
  app/controllers/project/project_heritage_controller.rb
  app/models/project.rb
  app/views/project/heritage/show.html.erb
  app/views/project/project_heritage/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/heritage_controller_spec.rb
Labels: ruby, tech debt

#310 Added integration test for project involvement controller
  app/controllers/project/involvement_controller.rb
  app/controllers/project/project_involvement_controller.rb
  app/models/project.rb
  app/views/project/involvement/show.html.erb
  app/views/project/project_involvement/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/involvement_controller_spec.rb
Labels: ruby, tech debt
