Repository heritagefund/funding-frontend, pull requests merged in 2020-03, with the labels that each got.

#311 Added integration tests for project declaration controller
  app/controllers/project/declaration_controller.rb
  app/controllers/project/project_declaration_controller.rb
  app/models/project.rb
  app/views/project/declaration/show_confirm_declaration.html.erb
  app/views/project/declaration/show_declaration.html.erb
  app/views/project/project_declaration/show_confirm_declaration.html.erb
  app/views/project/project_declaration/show_declaration.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/declaration_controller_spec.rb
Labels: ruby, tech debt

#313 Abstracted strings from dashboard page
  app/views/dashboard/show.html.erb
  config/locales/dashboard.yml
  spec/features/organisation_spec.rb
  spec/features/project_spec.rb
Labels: ruby

#315 Adds the 'Upload your governing documents' question to the flow
  app/assets/stylesheets/components/_list.scss
  app/controllers/project/governing_documents_controller.rb
  app/controllers/project/project_check_answers_controller.rb
  app/javascript/error-handling/index.js
  app/jobs/application_to_salesforce_job.rb
  app/models/project.rb
  app/views/project/governing_documents/show.html.erb
  app/views/project/governing_documents/show.js.erb
  config/locales/en.yml
  config/locales/governing_document.yml
  config/routes.rb
  spec/controllers/project/governing_documents_controller_spec.rb
  spec/features/project_spec.rb
Labels: enhancement, ruby

#318 Moved user research declaration to confirm declaration page
  app/controllers/project/declaration_controller.rb
  app/views/project/declaration/show_confirm_declaration.html.erb
  app/views/project/declaration/show_declaration.html.erb
  spec/controllers/project/declaration_controller_spec.rb
Labels: enhancement, ruby

#317 Added integration tests for application_submitted controller
  app/controllers/project/application_submitted_controller.rb
  app/controllers/project/project_application_submitted_controller.rb
  app/views/project/application_submitted/show.html.erb
  app/views/project/project_application_submitted/show.html.erb
  config/locales/application_submitted.yml
  config/routes.rb
  spec/controllers/project/application_submitted_controller_spec.rb
Labels: ruby, tech debt

#316 Added project capital works integration test
  app/controllers/project/capital_works_controller.rb
  app/controllers/project/project_capital_works_controller.rb
  app/views/project/capital_works/show.html.erb
  app/views/project/capital_works/show.js.erb
  app/views/project/project_capital_works/show.html.erb
  config/routes.rb
  spec/controllers/project/capital_works_controller_spec.rb
Labels: ruby, tech debt

#321 Added integration tests for project outcomes controller
  app/controllers/project/outcomes_controller.rb
  app/models/project.rb
  app/views/project/outcomes/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/outcomes_controller_spec.rb
Labels: ruby, tech debt

#322 Added integration test for new project controller
  app/controllers/project/new_project_controller.rb
  spec/controllers/project/new_project_controller_spec.rb
Labels: ruby, tech debt

#325 Added integration tests for project permission controller
  app/controllers/project/permission_controller.rb
  app/controllers/project/project_permission_controller.rb
  app/views/project/permission/show.html.erb
  app/views/project/project_permission/show.html.erb
  config/routes.rb
  spec/controllers/project/permission_controller_spec.rb
Labels: ruby, tech debt

#327 Removed superfluous project list files and references
  app/controllers/project/project_list_controller.rb
  app/helpers/project/project_list_helper.rb
  app/views/project/project_list/project_list.html.erb
  config/routes.rb
Labels: ruby, tech debt

#328 Added integration tests for project volunteers controller
  app/controllers/project/project_volunteers_controller.rb
  app/controllers/project/volunteers_controller.rb
  app/views/project/project_volunteers/show.html.erb
  app/views/project/volunteers/show.html.erb
  config/routes.rb
  spec/controllers/project/volunteers_controller_spec.rb
  spec/factories/volunteers.rb
Labels: ruby, tech debt

#330 Added integration tests for project non-cash contributions controller
  app/controllers/project/non_cash_contributions_controller.rb
  app/controllers/project/project_non_cash_contributions_controller.rb
  app/views/project/non_cash_contributions/question.html.erb
  app/views/project/non_cash_contributions/show.html.erb
  app/views/project/project_non_cash_contributions/question.html.erb
  app/views/project/project_non_cash_contributions/show.html.erb
  config/routes.rb
  spec/controllers/project/non_cash_contributions_spec.rb
  spec/factories/non_cash_contributions.rb
Labels: ruby, tech debt

#331 Added integration tests for evidence of support controller
  app/controllers/project/evidence_of_support_controller.rb
  app/controllers/project/project_support_evidence_controller.rb
  app/models/evidence_of_support.rb
  app/views/project/evidence_of_support/show.html.erb
  app/views/project/evidence_of_support/show.js.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/evidence_of_support_controller_spec.rb
  spec/factories/evidence_of_support.rb
Labels: ruby, tech debt

#334 Updated remaining page titles to use partial
  app/views/dashboard/show.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/show.html.erb
  app/views/organisation/about/about.html.erb
  app/views/organisation/about/address_results.html.erb
  app/views/organisation/about/postcode_lookup.html.erb
  app/views/project/application_submitted/show.html.erb
  app/views/project/grant_request/show.html.erb
  app/views/project/project_cash_contribution/question.html.erb
  app/views/project/project_costs/show.html.erb
  app/views/project/project_dates/show.html.erb
  app/views/project/project_location/address_results.html.erb
  app/views/project/project_location/entry.html.erb
  app/views/project/project_location/postcode_lookup.html.erb
  app/views/project/project_location/project_location.html.erb
  app/views/user/address/address_results.html.erb
  app/views/user/address/postcode_lookup.html.erb
  app/views/user/address/show.html.erb
  app/views/user/details/show.html.erb
Labels: ruby, tech debt

#337 Added integration tests for cash contributions controller
  app/controllers/project/cash_contributions_controller.rb
  app/controllers/project/project_cash_contribution_controller.rb
  app/models/cash_contribution.rb
  app/views/project/cash_contributions/question.html.erb
  app/views/project/cash_contributions/show.html.erb
  app/views/project/cash_contributions/show.js.erb
  app/views/project/project_cash_contribution/question.html.erb
  app/views/project/project_cash_contribution/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/cash_contributions_controller_spec.rb
Labels: ruby, tech debt

#343 Added tests for project and organisation controller concerns
  app/controllers/concerns/organisation_context.rb
  app/controllers/concerns/project_context.rb
  spec/controllers/concerns/organisation_context_spec.rb
  spec/controllers/concerns/project_context_spec.rb
Labels: ruby, tech debt

#344 Added integration tests for project check answers controller
  app/controllers/project/check_answers_controller.rb
  app/controllers/project/project_check_answers_controller.rb
  app/views/project/check_answers/_best_placed.html.erb
  app/views/project/check_answers/_capital_work.html.erb
  app/views/project/check_answers/_cash_contributions.html.erb
  app/views/project/check_answers/_change_link.html.erb
  app/views/project/check_answers/_community_matters.html.erb
  app/views/project/check_answers/_costs.html.erb
  app/views/project/check_answers/_description.html.erb
  app/views/project/check_answers/_difference.html.erb
  app/views/project/check_answers/_end_date.html.erb
  app/views/project/check_answers/_evidence_of_support.html.erb
  app/views/project/check_answers/_heritage.html.erb
  app/views/project/check_answers/_involvement.html.erb
  app/views/project/check_answers/_location.html.erb
  app/views/project/check_answers/_non_cash_contributions.html.erb
  app/views/project/check_answers/_other_outcomes.html.erb
  app/views/project/check_answers/_permission.html.erb
  app/views/project/check_answers/_start_date.html.erb
  app/views/project/check_answers/_title.html.erb
  app/views/project/check_answers/_volunteers.html.erb
  app/views/project/check_answers/show.html.erb
  app/views/project/project_check_answers/show.html.erb
  config/routes.rb
  spec/controllers/project/check_answers_controller_spec.rb
Labels: ruby, tech debt

#349 Added missing error elements to capital works view
  app/views/project/capital_works/show.html.erb
  app/views/project/capital_works/show.js.erb
Labels: bug

#350 Fixed a TODO on the user details controller
  app/controllers/user/details_controller.rb
Labels: ruby, tech debt

#362 Added fix for IE11 AJAX handling
  app/controllers/project/capital_works_controller.rb
  app/controllers/project/check_answers_controller.rb
  app/views/partials/_direct_file_upload_hooks.js.erb
  app/views/project/accounts/show.html.erb
  app/views/project/capital_works/show.html.erb
  app/views/project/cash_contributions/show.html.erb
  app/views/project/evidence_of_support/show.html.erb
  app/views/project/governing_documents/show.html.erb
  spec/controllers/project/check_answers_controller_spec.rb
Labels: bug

#365 Added a migration to add Flipper tables
  db/migrate/20200330102720_create_flipper_tables.rb
  db/schema.rb
Labels: ruby
