Repository heritagefund/funding-frontend, pull requests merged in 2020-04, with the labels that each got.

#366 Feature/frontend changes
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/project/declaration_controller.rb
  app/views/dashboard/show.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/project/declaration/show_confirm_declaration.html.erb
  config/initializers/flipper.rb
  config/routes.rb
  db/migrate/20200401123655_add_bau_gate.rb
  db/schema.rb
  spec/controllers/project/declaration_controller_spec.rb
  spec/features/about_you_spec.rb
  spec/features/organisation_spec.rb
  spec/features/project_spec.rb
Labels: ruby

#369 Configure RSpec to no longer expose the DSL globally
  spec/controllers/concerns/organisation_context_spec.rb
  spec/controllers/concerns/project_context_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/health_controller_spec.rb
  spec/controllers/organisation/mission_controller_spec.rb
  spec/controllers/organisation/numbers_controller_spec.rb
  spec/controllers/organisation/signatories_controller_spec.rb
  spec/controllers/organisation/summary_controller_spec.rb
  spec/controllers/organisation/type_controller_spec.rb
  spec/controllers/project/accounts_controller_spec.rb
  spec/controllers/project/application_submitted_controller_spec.rb
  spec/controllers/project/best_placed_controller_spec.rb
  spec/controllers/project/capital_works_controller_spec.rb
  spec/controllers/project/cash_contributions_controller_spec.rb
  spec/controllers/project/check_answers_controller_spec.rb
  spec/controllers/project/costs_controller_spec.rb
  spec/controllers/project/dates_controller_spec.rb
  spec/controllers/project/declaration_controller_spec.rb
  spec/controllers/project/description_controller_spec.rb
  spec/controllers/project/difference_controller_spec.rb
  spec/controllers/project/evidence_of_support_controller_spec.rb
  spec/controllers/project/governing_documents_controller_spec.rb
  spec/controllers/project/grant_request_controller_spec.rb
  spec/controllers/project/heritage_controller_spec.rb
  spec/controllers/project/involvement_controller_spec.rb
  spec/controllers/project/location_controller_spec.rb
  spec/controllers/project/matter_controller_spec.rb
  spec/controllers/project/new_project_controller_spec.rb
  spec/controllers/project/non_cash_contributions_controller_spec.rb
  spec/controllers/project/outcomes_controller_spec.rb
  spec/controllers/project/permission_controller_spec.rb
  spec/controllers/project/title_controller_spec.rb
  spec/controllers/project/volunteers_controller_spec.rb
  spec/controllers/released_form_controller_spec.rb
  spec/controllers/static_pages_controller_spec.rb
  spec/helpers/postcode_helper_spec.rb
  spec/helpers/project/calculate_total_helper_spec.rb
  spec/jobs/application_attachments_to_salesforce_job_spec.rb
  spec/jobs/application_to_salesforce_job_spec.rb
  spec/spec_helper.rb
Labels: ruby, tech debt

#368 Added validation for negative integers
  app/models/cash_contribution.rb
  app/models/non_cash_contribution.rb
  app/models/project_cost.rb
  app/models/volunteer.rb
  app/views/project/cash_contributions/show.html.erb
  app/views/project/non_cash_contributions/show.html.erb
  app/views/project/volunteers/show.html.erb
  config/locales/en.yml
  spec/controllers/project/cash_contributions_controller_spec.rb
  spec/controllers/project/costs_controller_spec.rb
  spec/controllers/project/non_cash_contributions_controller_spec.rb
  spec/controllers/project/volunteers_controller_spec.rb
Labels: ruby, tech debt

#377 Added isAlsoApplicant flag to Salesforce payload
  app/models/legal_signatory.rb
  app/models/project.rb
  spec/models/project_spec.rb
Labels: enhancement, ruby

#379 Send Devise notifications asynchronously
  app/models/user.rb
Labels: ruby, tech debt

#386 Reinstates Devise asynchronous sending
  app/mailers/notify_mailer.rb
  app/models/user.rb
Labels: bug, ruby

#390 Added configuration for UAT environment
  Gemfile
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/uat.rb
  config/secrets.yml
  config/storage.yml
  config/webpacker.yml
  manifest-uat.yml
Labels: enhancement, ruby
