Repository heritagefund/funding-frontend, pull requests merged in 2020-08, with the labels that each got.

#442 Abstracted content from new application page
  app/views/new_application/show.html.erb
  config/locales/new_application/en.yml
Labels: enhancement, ruby

#443 Removed TODOs from codebase
  app/models/legal_signatory.rb
  app/models/project.rb
  app/views/address/address_results.html.erb
  app/views/address/postcode_lookup.html.erb
  app/views/address/show.html.erb
  app/views/funding_application/hef_loan/form/partials/_section_6.html.erb
  app/views/organisation/signatories/show.html.erb
  app/views/partials/_direct_file_upload_hooks.js.erb
  app/views/project/cash_contributions/show.html.erb
  app/views/project/check_answers/_capital_work.html.erb
  app/views/project/costs/show.html.erb
  app/views/project/evidence_of_support/show.html.erb
  app/views/project/non_cash_contributions/show.html.erb
  app/views/project/volunteers/show.html.erb
  config/environments/staging.rb
  config/environments/uat.rb
  spec/features/project_spec.rb
Labels: ruby, tech debt

#444 Abstracted content from registration flow
  app/views/dashboard/show.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/partials/_signup-panel.html.erb
  app/views/project/declaration/show_confirm_declaration.html.erb
  app/views/user/details/show.html.erb
  app/views/user/registrations/edit.html.erb
  app/views/user/registrations/new.html.erb
  config/locales/covid_banner/en.yml
  config/locales/dashboard/en.yml
  config/locales/devise/confirmations/new/en.yml
  config/locales/devise/passwords/edit/en.yml
  config/locales/devise/passwords/new/en.yml
  config/locales/devise/sessions/new/en.yml
  config/locales/devise/unlocks/new/en.yml
  config/locales/user/details/show/en.yml
  config/locales/user/registrations/edit/en.yml
  config/locales/user/registrations/new/en.yml
Labels: enhancement, ruby

#445 Feature/alt finance form abstracted content
  app/views/funding_application/hef_loan/form/partials/_section_2.html.erb
  app/views/funding_application/hef_loan/form/partials/_section_3.html.erb
  app/views/funding_application/hef_loan/form/partials/_section_4.html.erb
  app/views/funding_application/hef_loan/form/partials/_section_5.html.erb
  app/views/funding_application/hef_loan/form/partials/_section_6.html.erb
  app/views/funding_application/hef_loan/form/show.html.erb
  config/locales/en.yml
  config/locales/funding_application/hef_loan/form/en.yml
Labels: content, enhancement, ruby

#447 Updated content on alternative finance start page
  app/views/funding_application/hef_loan/start/show.html.erb
  config/locales/funding_application/hef_loan/start/cy.yml
  config/locales/funding_application/hef_loan/start/en.yml
Labels: content, enhancement

#446 Added RuboCop and dependencies to Gemfile
  Gemfile
  Gemfile.lock
Labels: dependencies, tech debt

#448 Updated govuk-frontend to 3.8.0
  package.json
  yarn.lock
Labels: dependencies

#449 Updated Welsh content for alternative finance start page
  config/locales/funding_application/hef_loan/start/cy.yml
Labels: content

#439 Updated @rails/webpacker to ^5.1.1
  package.json
  yarn.lock
Labels: dependencies

#450 Linted address_controller.rb
  .rubocop.yml
  app/controllers/address_controller.rb
Labels: ruby, tech debt

#452 Added Jest package and tests for JavaScript error-handling
  app/javascript/error-handling/index.js
  package.json
  spec/javascript/error-handling/index.spec.js
  yarn.lock
Labels: javascript, tech debt, tests

#453 Updated README.md
  README.md
Labels: documentation

#454 Linted new_application_controller.rb
  app/controllers/new_application_controller.rb
Labels: ruby, tech debt

#455 Added step to run Jest tests in CI/CD GitHub Action
  .github/workflows/continuous-integration-workflow.yml
Labels: ci/cd, enhancement

#456 Added automated tests for /cookie-functions.js
  app/javascript/cookie-banner/cookie-functions.js
  package.json
  spec/javascript/cookie-banner/cookie-functions.spec.js
Labels: javascript, tech debt, tests

#457 Updated locale_helper param check to be more robust
  app/helpers/locale_helper.rb
Labels: bug, ruby

#458 Refactored file upload handling hooks
  app/javascript/error-handling/index.js
  app/javascript/file-upload-handling/index.js
  app/javascript/packs/application.js
  app/views/funding_application/hef_loan/supporting_documents/show.html.erb
  app/views/layouts/application.html.erb
  app/views/partials/_direct_file_upload_hooks.js.erb
  app/views/partials/_file_upload_error.html.erb
  app/views/partials/_file_upload_error_summary.html.erb
  app/views/project/accounts/show.html.erb
  app/views/project/capital_works/show.html.erb
  app/views/project/cash_contributions/show.html.erb
  app/views/project/evidence_of_support/show.html.erb
  app/views/project/governing_documents/show.html.erb
Labels: javascript, tech debt

#464 Added Gems for automated accessibility testing
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
Labels: dependencies, enhancement, ruby

#466 Updated OS declaration COVID-19 banner content
  app/views/project/declaration/show_confirm_declaration.html.erb
Labels: enhancement, ruby

#467 Fixed bug on dashboard controller where no organisation is present
  app/controllers/dashboard_controller.rb
Labels: bug, ruby

#465 Linted controllers/concerns files
  .rubocop.yml
  app/controllers/concerns/funding_application_context.rb
  app/controllers/concerns/object_errors_logger.rb
  app/controllers/concerns/organisation_context.rb
  app/controllers/concerns/postcode_lookup.rb
  app/controllers/concerns/project_context.rb
Labels: ruby, tech debt

#469 Bumped govuk-frontend from 3.8.0 to 3.8.1
  package.json
  yarn.lock
Labels: dependencies

#470 Added an additional scenario for dashboard_controller spec
  spec/controllers/dashboard_controller_spec.rb
Labels: ruby, tech debt, tests

#468 Fixed RuboCop violations in funding_application controllers
  .rubocop.yml
  app/controllers/funding_application/hef_loan/application_submitted_controller.rb
  app/controllers/funding_application/hef_loan/declaration_controller.rb
  app/controllers/funding_application/hef_loan/form_controller.rb
  app/controllers/funding_application/hef_loan/start_controller.rb
  app/controllers/funding_application/hef_loan/supporting_documents_controller.rb
  app/models/application/common/funding_application.rb
Labels: ruby, tech debt
