Repository heritagefund/funding-frontend, pull requests merged in 2020-06, with the labels that each got.

#398 Updated Ruby-on-Rails Gem version
  Gemfile
  Gemfile.lock
Labels: dependencies

#401 Added UAT environment to CI pipeline
  .github/workflows/continuous-integration-workflow.yml
Labels: enhancement

#402 Refactoring for a common approach to funding programmes
  app/controllers/funding_application/hef_loan/form_controller.rb
  app/models/address.rb
  app/models/application/common/funding_application.rb
  app/models/application/common/funding_application_address.rb
  app/views/funding_application/hef_loan/form/show.html.erb
  config/application.rb
  config/routes.rb
  db/migrate/20200602083556_create_addresses.rb
  db/migrate/20200602083558_create_funding_applications.rb
  db/migrate/20200602083559_create_funding_application_addresses.rb
  db/schema.rb
Labels: enhancement, ruby

#404 Feature/additional toggles
  app/controllers/concerns/funding_application_context.rb
  app/controllers/dashboard_controller.rb
  app/controllers/funding_application/hef_loan/form_controller.rb
  app/controllers/funding_application/hef_loan/start_controller.rb
  app/controllers/home_controller.rb
  app/controllers/new_application_controller.rb
  app/controllers/project/declaration_controller.rb
  app/controllers/project/start_controller.rb
  app/helpers/organisation_helper.rb
  app/models/new_application.rb
  app/views/dashboard/show.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/funding_application/hef_loan/start/show.html.erb
  app/views/new_application/show.html.erb
  app/views/organisation/summary/show.html.erb
  app/views/project/declaration/show_confirm_declaration.html.erb
  app/views/project/start/show.html.erb
  config/locales/dashboard.yml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/project/declaration_controller_spec.rb
  spec/features/about_you_spec.rb
  spec/features/organisation_spec.rb
  spec/features/project_spec.rb
Labels: enhancement, ruby

#405 added migration to remove bau flipper row
  config/initializers/flipper.rb
  db/migrate/20200611140500_remove_bau_flipper_rows.rb
  db/schema.rb
Labels: enhancement, ruby

#406 Added RSpec tests for alternative funding
  app/controllers/concerns/funding_application_context.rb
  app/controllers/dashboard_controller.rb
  app/controllers/new_application_controller.rb
  app/models/new_application.rb
  spec/controllers/concerns/funding_application_context_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/funding_application/hef_loan/form_controller_spec.rb
  spec/controllers/funding_application/hef_loan/start_controller_spec.rb
  spec/controllers/new_application_controller_spec.rb
  spec/controllers/project/start_controller_spec.rb
  spec/factories/funding_applications.rb
  spec/helpers/organisation_helper_spec.rb
Labels: ruby

#407 added migrations
  db/migrate/20200619081912_create_people.rb
  db/migrate/20200619082127_create_people_addresses.rb
  db/migrate/20200619105103_add_foreign_key_to_users.rb
  db/migrate/20200623152611_create_users_addresses.rb
  db/schema.rb
Labels: enhancement, ruby

#408 Added Gems to enable debugging in VSCode
  Gemfile
  Gemfile.lock
Labels: dependencies
