Repository heritagefund/funding-frontend, pull requests merged in 2021-02, with the labels that each got.

#538 Added SalesforceApi library
  config/application.rb
  lib/apis/salesforce/salesforce_api.rb
  spec/lib/salesforce/salesforce_api_spec.rb
Labels: enhancement, ruby, tests

#539 Added database migration to add missing payment_details columns
  db/migrate/20210203140613_add_columns_to_payment_details.rb
  db/schema.rb
Labels: enhancement, ruby

#543 Wired up 'tell us what you have spent' page
  app/views/funding_application/payment_requests/evidence_of_spend/show.html.erb
Labels: enhancement, ruby

#544 Fixed issue where payment_requests_spend row was not being created
  app/controllers/funding_application/payment_requests/add_item_of_spend_controller.rb
Labels: bug, ruby

#546 Added wiring of spend so far totals on review project spend page
  app/views/funding_application/payment_requests/confirm_evidence_of_spend/show.html.erb
Labels: enhancement, ruby

#545 Abstract footer and content
  app/views/layouts/application.html.erb
  app/views/partials/_footer.html.erb
  config/locales/partials/footer/cy.yml
  config/locales/partials/footer/en.yml
Labels: ruby, tech debt

#549 1761-cookie-content-translation
  app/views/help/cookie_details.html.erb
  config/locales/help/cookie_details/cy.yml
  config/locales/help/cookie_details/en.yml
Labels: ruby, tech debt

#550 Refactored confirm evidence of spend page to account for all costs
  app/controllers/funding_application/payment_requests/confirm_evidence_of_spend_controller.rb
  app/views/funding_application/payment_requests/confirm_evidence_of_spend/show.html.erb
Labels: enhancement, ruby

#556 Wiring of payment request submitted page including logic
  app/controllers/funding_application/payment_requests/confirm_evidence_of_spend_controller.rb
  app/controllers/funding_application/payment_requests/submitted_controller.rb
  app/helpers/payment_details_and_request_helper.rb
  app/views/funding_application/payment_requests/confirm_evidence_of_spend/show.html.erb
  app/views/funding_application/payment_requests/submitted/show.html.erb
  config/routes.rb
Labels: enhancement, ruby

#558 Added to_json method for PaymentRequest model
  app/models/payment_request.rb
Labels: enhancement, ruby

#551 1760 - cookie banner translations
  app/views/partials/_cookie_banner.html.erb
  config/locales/partials/cookie_banner/cy.yml
  config/locales/partials/cookie_banner/en.yml
Labels: ruby, tech debt

#553 2285 - Abstract strings from project heritage page
  app/views/funding_application/gp_project/heritage/show.html.erb
  config/locales/funding_application/gp_project/heritage/cy.yml
  config/locales/funding_application/gp_project/heritage/en.yml
Labels: ruby, tech debt

#554 2286-abstract-strings-from-project-mandatory-outcome-page
  app/views/funding_application/gp_project/involvement/show.html.erb
  config/locales/funding_application/gp_project/involvement/cy.yml
  config/locales/funding_application/gp_project/involvement/en.yml
Labels: ruby, tech debt

#552 2284 support page translations
  app/views/support/question_or_feedback.html.erb
  app/views/support/report_a_problem.html.erb
  app/views/support/show.html.erb
  config/locales/cy.yml
  config/locales/en.yml
  config/locales/support/cy.yml
  config/locales/support/en.yml
  config/locales/support/question_or_feedback/cy.yml
  config/locales/support/question_or_feedback/en.yml
  config/locales/support/report_a_problem/cy.yml
  config/locales/support/report_a_problem/en.yml
Labels: ruby, tech debt

#555 Feature/2287 community importance
  app/views/funding_application/gp_project/matter/show.html.erb
  config/locales/funding_application/gp_project/matter/cy.yml
  config/locales/funding_application/gp_project/matter/en.yml
Labels: ruby, tech debt
