Repository heritagefund/funding-frontend, pull requests merged in 2021-04, with the labels that each got.

#706 Added application submitted page for open medium grant journey
  app/controllers/funding_application/gp_open_medium/application_submitted_controller.rb
  app/views/funding_application/gp_open_medium/application_submitted/show.html.erb
  config/routes.rb
Labels: enhancement, ruby

#703 Added acquisitions question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/acquisition_controller.rb
  app/controllers/funding_application/gp_open_medium/capital_works_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/acquisition/show.html.erb
  app/views/partials/funding_application/_acquisition_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/acquisition/en.yml
  config/routes.rb
  db/migrate/20210406074311_add_acquisition_to_gp_open_medium.rb
  db/schema.rb
Labels: enhancement, ruby

#704 Added capital work question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/capital_works_controller.rb
  app/javascript/error-handling/index.js
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/capital_works/show.html.erb
  app/views/funding_application/gp_open_medium/capital_works/show.js.erb
  app/views/funding_application/gp_project/capital_works/show.html.erb
  app/views/partials/funding_application/_capital_works_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_project/capital_works/en.yml
  spec/javascript/error-handling/index.spec.js
Labels: enhancement, javascript, ruby

#702 Added formal heritage designations question to medium grants
  app/controllers/funding_application/gp_open_medium/heritage_designations_controller.rb
  app/controllers/funding_application/gp_open_medium/heritage_formal_designation_description_controller.rb
  app/models/heritage_designation.rb
  app/models/open_medium.rb
  app/models/open_medium_heritage_designation.rb
  app/views/funding_application/gp_open_medium/heritage_designations/show.html.erb
  app/views/funding_application/gp_open_medium/heritage_formal_designation_description/show.html.erb
  app/views/partials/funding_application/_heritage_designations_question.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_1_or_a_listed_building.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_1_park_or_garden.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_or_b_listed_building.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_or_c_listed_building.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_park_or_garden.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_star_park_or_garden.html.erb
  app/views/partials/funding_application/heritage_designations/_local_list.html.erb
  app/views/partials/funding_application/heritage_designations/_other.html.erb
  app/views/partials/funding_application/heritage_designations/_registered_historic_ship.html.erb
  app/views/partials/funding_application/heritage_designations/_scheduled_ancient_monument.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/heritage_designations/en.yml
  config/routes.rb
  db/migrate/20210406074312_create_heritage_designations.rb
  db/migrate/20210406074313_add_heritage_designations.rb
  db/migrate/20210406074314_create_gp_open_medium_heritage_dsgntns.rb
  db/migrate/20210406074315_add_designation_columns_to_open_medium.rb
  db/schema.rb
Labels: enhancement, ruby

#705 Added capital works ownership question to medium grant journey
  app/controllers/funding_application/gp_open_medium/ownership_controller.rb
  app/javascript/error-handling/index.js
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/ownership/show.html.erb
  app/views/funding_application/gp_open_medium/ownership/show.js.erb
  app/views/partials/funding_application/_ownership_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/ownership/en.yml
  config/routes.rb
  db/migrate/20210406094942_add_ownership_type_to_gp_open_medium.rb
  db/schema.rb
Labels: enhancement, javascript, ruby

#707 Added volunteers question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/volunteers_controller.rb
  app/models/application/common/funding_application.rb
  app/models/funding_applications_vlntr.rb
  app/models/volunteer.rb
  app/views/funding_application/gp_open_medium/volunteers/show.html.erb
  app/views/partials/funding_application/volunteers/_question.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210406120100_create_funding_applications_vlntrs.rb
  db/migrate/20210406132841_set_project_nullable_on_volunteers.rb
  db/schema.rb
Labels: enhancement, ruby

#708 Added partnerships question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/is_partnership_controller.rb
  app/controllers/funding_application/gp_open_medium/partnership_controller.rb
  app/javascript/error-handling/index.js
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/is_partnership/show.html.erb
  app/views/funding_application/gp_open_medium/partnership/show.html.erb
  app/views/funding_application/gp_open_medium/partnership/show.js.erb
  app/views/partials/funding_application/_governing_documents_question.html.erb
  app/views/partials/funding_application/_partnership_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/partnership/en.yml
  config/routes.rb
Labels: enhancement, javascript, ruby

#710 Added non-cash contributions page to open medium grant journey
  app/controllers/funding_application/gp_open_medium/non_cash_contributions_controller.rb
  app/models/application/common/funding_application.rb
  app/models/funding_applications_ncc.rb
  app/models/funding_applications_vlntr.rb
  app/models/non_cash_contribution.rb
  app/views/funding_application/gp_open_medium/non_cash_contributions/question.html.erb
  app/views/funding_application/gp_open_medium/non_cash_contributions/show.html.erb
  app/views/funding_application/gp_project/non_cash_contributions/show.html.erb
  app/views/partials/funding_application/non_cash_contributions/_add_question.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210408101428_create_funding_applications_nccs.rb
  db/migrate/20210408101538_set_project_nullable_on_non_cash_contributions.rb
  db/schema.rb
Labels: enhancement, ruby

#711 Added supporting evidence question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/evidence_of_support_controller.rb
  app/javascript/error-handling/index.js
  app/models/application/common/funding_application.rb
  app/models/evidence_of_support.rb
  app/models/funding_applications_evidence.rb
  app/views/funding_application/gp_open_medium/evidence_of_support/show.html.erb
  app/views/funding_application/gp_open_medium/evidence_of_support/show.js.erb
  app/views/funding_application/gp_project/evidence_of_support/show.html.erb
  app/views/partials/funding_application/evidence_of_support/_question.html.erb
  config/routes.rb
  db/migrate/20210408122205_create_funding_applications_eos.rb
  db/migrate/20210408122219_set_project_nullable_on_evidence.rb
  db/schema.rb
Labels: enhancement, javascript, ruby

#712 Added cash contributions question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/cash_contributions_controller.rb
  app/javascript/error-handling/index.js
  app/models/application/common/funding_application.rb
  app/models/cash_contribution.rb
  app/models/funding_applications_cc.rb
  app/views/funding_application/gp_open_medium/cash_contributions/question.html.erb
  app/views/funding_application/gp_open_medium/cash_contributions/show.html.erb
  app/views/funding_application/gp_open_medium/cash_contributions/show.js.erb
  app/views/funding_application/gp_project/cash_contributions/show.html.erb
  app/views/funding_application/gp_project/cash_contributions/show.js.erb
  app/views/partials/funding_application/cash_contributions/_add_question.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210408135501_create_funding_applications_ccs.rb
  db/migrate/20210408135544_set_project_nullable_on_cash_contributions.rb
  db/schema.rb
Labels: enhancement, javascript, ruby

#713 Added project costs question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/costs_controller.rb
  app/models/application/common/funding_application.rb
  app/models/funding_applications_cost.rb
  app/models/project_cost.rb
  app/views/funding_application/gp_open_medium/costs/show.html.erb
  app/views/funding_application/gp_project/costs/show.html.erb
  app/views/partials/funding_application/costs/_page_upper.html.erb
  app/views/partials/funding_application/costs/_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_project/costs/cy.yml
  config/locales/funding_application/gp_project/costs/en.yml
  config/routes.rb
  db/migrate/20210409062834_create_funding_applications_costs.rb
  db/migrate/20210409062846_set_project_nullable_on_costs.rb
  db/migrate/20210409065524_add_vat_to_project_costs.rb
  db/schema.rb
  spec/controllers/funding_application/gp_project/costs_controller_spec.rb
Labels: enhancement, ruby

#714 Added check your answers stub page to open medium grant journey
  app/controllers/funding_application/gp_open_medium/best_placed_controller.rb
  app/controllers/funding_application/gp_open_medium/check_answers_controller.rb
  app/views/funding_application/gp_open_medium/check_answers/show.html.erb
  app/views/funding_application/gp_open_medium/cost_recovery/show.html.erb
  app/views/funding_application/gp_open_medium/governing_documents/show.html.erb
  config/routes.rb
Labels: bug, enhancement, ruby

#715 Fixed bug in GpOpenMedium declaration controller
  app/controllers/funding_application/gp_open_medium/declaration_controller.rb
Labels: bug, ruby

#717 Added narrative field to jobs question on open medium journey
  app/controllers/funding_application/gp_open_medium/jobs_controller.rb
  app/javascript/error-handling/index.js
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/jobs/show.html.erb
  app/views/funding_application/gp_open_medium/jobs/show.js.erb
  app/views/partials/funding_application/_jobs_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/jobs/en.yml
Labels: enhancement, javascript, ruby

#718 Refactored heritage designations to match Salesforce validations
  app/models/open_medium.rb
  app/views/partials/funding_application/heritage_designations/_grade_1_or_a_listed_building.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_1_park_or_garden.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_or_b_listed_building.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_or_c_listed_building.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_park_or_garden.html.erb
  app/views/partials/funding_application/heritage_designations/_grade_2_star_park_or_garden.html.erb
  app/views/partials/funding_application/heritage_designations/_local_list.html.erb
  app/views/partials/funding_application/heritage_designations/_other.html.erb
  app/views/partials/funding_application/heritage_designations/_registered_historic_ship.html.erb
  app/views/partials/funding_application/heritage_designations/_scheduled_ancient_monument.html.erb
  config/locales/en.yml
  db/migrate/20210414073032_fix_designation_data_types.rb
  db/schema.rb
Labels: enhancement, ruby

#719 Added check your answers to open medium grant journey
  app/controllers/funding_application/gp_open_medium/check_answers_controller.rb
  app/views/funding_application/gp_open_medium/check_answers/show.html.erb
  app/views/partials/funding_application/check_answers/_accounts.html.erb
  app/views/partials/funding_application/check_answers/_acknowledgement.html.erb
  app/views/partials/funding_application/check_answers/_acquisition.html.erb
  app/views/partials/funding_application/check_answers/_at_risk.html.erb
  app/views/partials/funding_application/check_answers/_at_risk_description.html.erb
  app/views/partials/funding_application/check_answers/_best_placed.html.erb
  app/views/partials/funding_application/check_answers/_board_members_or_trustees.html.erb
  app/views/partials/funding_application/check_answers/_capital_work.html.erb
  app/views/partials/funding_application/check_answers/_cash_contributions.html.erb
  app/views/partials/funding_application/check_answers/_change_link.html.erb
  app/views/partials/funding_application/check_answers/_community_matters.html.erb
  app/views/partials/funding_application/check_answers/_costs.html.erb
  app/views/partials/funding_application/check_answers/_description.html.erb
  app/views/partials/funding_application/check_answers/_difference.html.erb
  app/views/partials/funding_application/check_answers/_end_date.html.erb
  app/views/partials/funding_application/check_answers/_environmental_impacts.html.erb
  app/views/partials/funding_application/check_answers/_evaluation.html.erb
  app/views/partials/funding_application/check_answers/_evidence_of_support.html.erb
  app/views/partials/funding_application/check_answers/_first_fund_application.html.erb
  app/views/partials/funding_application/check_answers/_full_cost_recovery.html.erb
  app/views/partials/funding_application/check_answers/_governing_documents.html.erb
  app/views/partials/funding_application/check_answers/_heritage.html.erb
  app/views/partials/funding_application/check_answers/_heritage_attracts_visitors.html.erb
  app/views/partials/funding_application/check_answers/_heritage_designations.html.erb
  app/views/partials/funding_application/check_answers/_involvement.html.erb
  app/views/partials/funding_application/check_answers/_jobs.html.erb
  app/views/partials/funding_application/check_answers/_location.html.erb
  app/views/partials/funding_application/check_answers/_main_purpose.html.erb
  app/views/partials/funding_application/check_answers/_management.html.erb
  app/views/partials/funding_application/check_answers/_non_cash_contributions.html.erb
  app/views/partials/funding_application/check_answers/_other_outcomes.html.erb
  app/views/partials/funding_application/check_answers/_partnership.html.erb
  app/views/partials/funding_application/check_answers/_partnership_details.html.erb
  app/views/partials/funding_application/check_answers/_permission.html.erb
  app/views/partials/funding_application/check_answers/_project_images.html.erb
  app/views/partials/funding_application/check_answers/_project_plan.html.erb
  app/views/partials/funding_application/check_answers/_received_advice.html.erb
  app/views/partials/funding_application/check_answers/_recent_project_reference.html.erb
  app/views/partials/funding_application/check_answers/_recent_project_title.html.erb
  app/views/partials/funding_application/check_answers/_social_media.html.erb
  app/views/partials/funding_application/check_answers/_spend_last_year.html.erb
  app/views/partials/funding_application/check_answers/_start_date.html.erb
  app/views/partials/funding_application/check_answers/_title.html.erb
  app/views/partials/funding_application/check_answers/_unrestricted_funds.html.erb
  app/views/partials/funding_application/check_answers/_vat_number.html.erb
  app/views/partials/funding_application/check_answers/_vat_registered.html.erb
  app/views/partials/funding_application/check_answers/_visitors_expected_per_year.html.erb
  app/views/partials/funding_application/check_answers/_visitors_in_last_financial_year.html.erb
  app/views/partials/funding_application/check_answers/_volunteers.html.erb
  app/views/partials/funding_application/check_answers/_why_now.html.erb
  app/views/partials/funding_application/check_answers/_work_briefs.html.erb
  config/locales/en.yml
  config/locales/funding_application/check_answers/en.yml
Labels: enhancement, ruby

#720 Updated Salesforce API client to handle medium grant submission
  app/controllers/funding_application/gp_open_medium/declaration_controller.rb
  app/helpers/funding_application_helper.rb
  db/migrate/20210414073033_add_external_ids.rb
  db/schema.rb
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby

#721 Attempted fix for Restforce file upload handling
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#722 Second attempt at Restforce file fix
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#723 Fixed issue with Restforce file uploads
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#724 Revert "Fixed issue with Restforce file uploads"
  lib/apis/salesforce/salesforce_api.rb
Labels: bug

#725 Fixes Restforce file attachments using Helper method
  app/helpers/application_helper.rb
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#726 Small fixes to open medium grant journey
  config/locales/funding_application/gp_project/declaration/en.yml
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#727 Fixed a bug in 'Your grant request' page of medium grant journey
  app/controllers/funding_application/gp_open_medium/grant_request_controller.rb
  app/views/funding_application/gp_open_medium/grant_request/show.html.erb
  config/locales/funding_application/gp_project/grant_request/en.yml
Labels: bug, ruby

#728 Fixed logic in 'first fund application' check answers partial
  app/views/partials/funding_application/check_answers/_first_fund_application.html.erb
Labels: bug, ruby

#730 Removed validation on jobs files uploads
  app/controllers/funding_application/gp_open_medium/jobs_controller.rb
Labels: bug, ruby

#729 Fixed incorrect link on medium grants start page
  app/views/funding_application/gp_open_medium/start/show.html.erb
  config/locales/new_application/en.yml
Labels: content

#731 Fixed redirect upon file upload on partnership page
  app/controllers/funding_application/gp_open_medium/partnership_controller.rb
  app/views/funding_application/gp_open_medium/capital_works/show.html.erb
  config/locales/funding_application/gp_project/capital_works/en.yml
Labels: bug, ruby

#732 Changed validation of previous project reference number
  app/models/open_medium.rb
Labels: bug, ruby

#733 Updated non-cash contribs view to direct to vlntrs
  app/views/funding_application/gp_open_medium/non_cash_contributions/show.html.erb
Labels: bug, ruby

#746 Fixed typo in partnership locale file
  config/locales/funding_application/gp_open_medium/partnership/en.yml
Labels: content

#745 Wired ownership question into open medium grant journey
  app/controllers/funding_application/gp_open_medium/capital_works_controller.rb
  app/controllers/funding_application/gp_open_medium/ownership_controller.rb
  app/views/funding_application/gp_open_medium/check_answers/show.html.erb
  app/views/partials/funding_application/check_answers/_ownership.html.erb
  config/locales/funding_application/check_answers/en.yml
Labels: ruby, tech debt

#747 Added filtering to Sentry JavaScript initialisation
  app/javascript/sentry/index.js
Labels: javascript, tech debt

#751 Added missing translation for heritage designation
  config/locales/funding_application/gp_open_medium/heritage_designations/cy.yml
  config/locales/funding_application/gp_open_medium/heritage_designations/en.yml
Labels: content

#749 Updated deprecated GitHub Action
  .github/workflows/continuous-integration-workflow.yml
  Gemfile
  Gemfile.lock
Labels: ci/cd, tech debt

#752 Revert "Updated deprecated GitHub Action"
  .github/workflows/continuous-integration-workflow.yml
  Gemfile
  Gemfile.lock
Labels: ci/cd

#750 Updated Dependabot configuration file
  dependabot.yml
Labels: ci/cd, tech debt

#748 Added Welsh translations for pre-application journeys
  config/locales/pre_application/pa_expression_of_interest/check_answers/cy.yml
  config/locales/pre_application/pa_expression_of_interest/check_answers/en.yml
  config/locales/pre_application/pa_expression_of_interest/heritage_focus/cy.yml
  config/locales/pre_application/pa_expression_of_interest/heritage_focus/en.yml
  config/locales/pre_application/pa_expression_of_interest/likely_submission_description/cy.yml
  config/locales/pre_application/pa_expression_of_interest/likely_submission_description/en.yml
  config/locales/pre_application/pa_expression_of_interest/overall_cost/cy.yml
  config/locales/pre_application/pa_expression_of_interest/overall_cost/en.yml
  config/locales/pre_application/pa_expression_of_interest/potential_funding_amount/cy.yml
  config/locales/pre_application/pa_expression_of_interest/potential_funding_amount/en.yml
  config/locales/pre_application/pa_expression_of_interest/previous_contact_name/cy.yml
  config/locales/pre_application/pa_expression_of_interest/programme_outcomes/cy.yml
  config/locales/pre_application/pa_expression_of_interest/programme_outcomes/en.yml
  config/locales/pre_application/pa_expression_of_interest/project_reasons/cy.yml
  config/locales/pre_application/pa_expression_of_interest/project_reasons/en.yml
  config/locales/pre_application/pa_expression_of_interest/project_timescales/cy.yml
  config/locales/pre_application/pa_expression_of_interest/project_timescales/en.yml
  config/locales/pre_application/pa_expression_of_interest/submitted/cy.yml
  config/locales/pre_application/pa_expression_of_interest/submitted/en.yml
  config/locales/pre_application/pa_expression_of_interest/what_project_does/cy.yml
  config/locales/pre_application/pa_expression_of_interest/what_project_does/en.yml
  config/locales/pre_application/pa_expression_of_interest/working_title/cy.yml
  config/locales/pre_application/pa_expression_of_interest/working_title/en.yml
  config/locales/pre_application/pa_project_enquiry/check_answers/cy.yml
  config/locales/pre_application/pa_project_enquiry/heritage_focus/cy.yml
  config/locales/pre_application/pa_project_enquiry/heritage_focus/en.yml
  config/locales/pre_application/pa_project_enquiry/potential_funding_amount/cy.yml
  config/locales/pre_application/pa_project_enquiry/potential_funding_amount/en.yml
  config/locales/pre_application/pa_project_enquiry/previous_contact_name/cy.yml
  config/locales/pre_application/pa_project_enquiry/programme_outcomes/cy.yml
  config/locales/pre_application/pa_project_enquiry/programme_outcomes/en.yml
  config/locales/pre_application/pa_project_enquiry/project_likely_cost/cy.yml
  config/locales/pre_application/pa_project_enquiry/project_likely_cost/en.yml
  config/locales/pre_application/pa_project_enquiry/project_participants/cy.yml
  config/locales/pre_application/pa_project_enquiry/project_participants/en.yml
  config/locales/pre_application/pa_project_enquiry/project_reasons/cy.yml
  config/locales/pre_application/pa_project_enquiry/project_reasons/en.yml
  config/locales/pre_application/pa_project_enquiry/project_timescales/cy.yml
  config/locales/pre_application/pa_project_enquiry/project_timescales/en.yml
  config/locales/pre_application/pa_project_enquiry/submitted/cy.yml
  config/locales/pre_application/pa_project_enquiry/submitted/en.yml
  config/locales/pre_application/pa_project_enquiry/what_project_does/cy.yml
  config/locales/pre_application/pa_project_enquiry/what_project_does/en.yml
  config/locales/pre_application/pa_project_enquiry/working_title/cy.yml
  config/locales/pre_application/pa_project_enquiry/working_title/en.yml
Labels: enhancement

#755  Bug/additional medium welsh fixes
  app/controllers/concerns/postcode_lookup.rb
  app/views/address/address_results.html.erb
  app/views/address/postcode_lookup.html.erb
  app/views/address/show.html.erb
  app/views/funding_application/gp_open_medium/cash_contributions/show.html.erb
  app/views/funding_application/gp_open_medium/non_cash_contributions/show.html.erb
  app/views/funding_application/gp_open_medium/volunteers/show.html.erb
  app/views/partials/_summary_errors_flash.html.erb
  app/views/partials/funding_application/check_answers/_accounts.html.erb
  app/views/partials/funding_application/check_answers/_acknowledgement.html.erb
  app/views/partials/funding_application/check_answers/_acquisition.html.erb
  app/views/partials/funding_application/check_answers/_at_risk.html.erb
  app/views/partials/funding_application/check_answers/_at_risk_description.html.erb
  app/views/partials/funding_application/check_answers/_best_placed.html.erb
  app/views/partials/funding_application/check_answers/_board_members_or_trustees.html.erb
  app/views/partials/funding_application/check_answers/_capital_work.html.erb
  app/views/partials/funding_application/check_answers/_community_matters.html.erb
  app/views/partials/funding_application/check_answers/_description.html.erb
  app/views/partials/funding_application/check_answers/_difference.html.erb
  app/views/partials/funding_application/check_answers/_end_date.html.erb
  app/views/partials/funding_application/check_answers/_environmental_impacts.html.erb
  app/views/partials/funding_application/check_answers/_evaluation.html.erb
  app/views/partials/funding_application/check_answers/_first_fund_application.html.erb
  app/views/partials/funding_application/check_answers/_full_cost_recovery.html.erb
  app/views/partials/funding_application/check_answers/_governing_documents.html.erb
  app/views/partials/funding_application/check_answers/_heritage.html.erb
  app/views/partials/funding_application/check_answers/_heritage_attracts_visitors.html.erb
  app/views/partials/funding_application/check_answers/_heritage_designations.html.erb
  app/views/partials/funding_application/check_answers/_involvement.html.erb
  app/views/partials/funding_application/check_answers/_jobs.html.erb
  app/views/partials/funding_application/check_answers/_main_purpose.html.erb
  app/views/partials/funding_application/check_answers/_management.html.erb
  app/views/partials/funding_application/check_answers/_partnership.html.erb
  app/views/partials/funding_application/check_answers/_partnership_details.html.erb
  app/views/partials/funding_application/check_answers/_permission.html.erb
  app/views/partials/funding_application/check_answers/_project_images.html.erb
  app/views/partials/funding_application/check_answers/_project_plan.html.erb
  app/views/partials/funding_application/check_answers/_received_advice.html.erb
  app/views/partials/funding_application/check_answers/_recent_project_reference.html.erb
  app/views/partials/funding_application/check_answers/_recent_project_title.html.erb
  app/views/partials/funding_application/check_answers/_social_media.html.erb
  app/views/partials/funding_application/check_answers/_spend_last_year.html.erb
  app/views/partials/funding_application/check_answers/_start_date.html.erb
  app/views/partials/funding_application/check_answers/_title.html.erb
  app/views/partials/funding_application/check_answers/_unrestricted_funds.html.erb
  app/views/partials/funding_application/check_answers/_vat_number.html.erb
  app/views/partials/funding_application/check_answers/_vat_registered.html.erb
  app/views/partials/funding_application/check_answers/_visitors_expected_per_year.html.erb
  app/views/partials/funding_application/check_answers/_visitors_in_last_financial_year.html.erb
  app/views/partials/funding_application/check_answers/_why_now.html.erb
  app/views/partials/funding_application/check_answers/_work_briefs.html.erb
  config/locales/address/address_details/cy.yml
  config/locales/address/address_details/en.yml
  config/locales/address/postcode/cy.yml
  config/locales/address/postcode/en.yml
  config/locales/funding_application/check_answers/cy.yml
  config/locales/funding_application/check_answers/en.yml
Labels: ruby, tech debt

#753 Fixed building society roll number validation
  app/models/payment_details.rb
  app/views/funding_application/bank_details/confirm/show.html.erb
  config/locales/en.yml
Labels: bug, ruby

#754 Updated name validation to account for Salesforce char limits
  app/models/legal_signatory.rb
  app/models/person.rb
  app/models/user.rb
  config/locales/en.yml
Labels: ruby, tech debt
