Repository heritagefund/funding-frontend, pull requests merged in 2021-03, with the labels that each got.

#579 Feature/2338 PEF & EOI content changes
  app/views/pre_application/expression_of_interest/submitted/show.html.erb
  app/views/pre_application/project_enquiry/submitted/show.html.erb
  config/locales/pre_application/pa_expression_of_interest/check_answers/en.yml
  config/locales/pre_application/pa_expression_of_interest/likely_submission_description/en.yml
  config/locales/pre_application/pa_expression_of_interest/overall_cost/en.yml
  config/locales/pre_application/pa_expression_of_interest/potential_funding_amount/en.yml
  config/locales/pre_application/pa_expression_of_interest/previous_contact_name/en.yml
  config/locales/pre_application/pa_expression_of_interest/programme_outcomes/en.yml
  config/locales/pre_application/pa_expression_of_interest/project_timescales/en.yml
  config/locales/pre_application/pa_expression_of_interest/submitted/en.yml
  config/locales/pre_application/pa_project_enquiry/check_answers/en.yml
  config/locales/pre_application/pa_project_enquiry/potential_funding_amount/en.yml
  config/locales/pre_application/pa_project_enquiry/previous_contact_name/en.yml
  config/locales/pre_application/pa_project_enquiry/project_likely_cost/en.yml
Labels: enhancement

#578 2303 - adds welsh translation to yml files
  app/views/funding_application/gp_project/cash_contributions/show.html.erb
  config/locales/cy.yml
  config/locales/funding_application/gp_project/cash_contributions/cy.yml
  config/locales/funding_application/gp_project/cash_contributions/question/cy.yml
  config/locales/funding_application/gp_project/check_answers/cy.yml
  config/locales/funding_application/gp_project/costs/cy.yml
  config/locales/funding_application/gp_project/evidence_of_support/cy.yml
  config/locales/funding_application/gp_project/grant_request/cy.yml
  config/locales/funding_application/gp_project/heritage/cy.yml
  config/locales/funding_application/gp_project/involvement/cy.yml
  config/locales/funding_application/gp_project/non_cash_contributions/cy.yml
  config/locales/help/cookie_details/cy.yml
  config/locales/partials/cookie_banner/cy.yml
  config/locales/partials/footer/cy.yml
  config/locales/partials/header/cy.yml
  config/locales/support/cy.yml
  config/locales/support/question_or_feedback/cy.yml
  config/locales/support/report_a_problem/cy.yml
Labels: enhancement

#588 Fixed incorrect locale key reference on supporting evidence view
  app/views/funding_application/gp_project/evidence_of_support/show.html.erb
  config/locales/en.yml
Labels: bug, ruby

#590 Abstracted remaining content from project costs view
  app/views/funding_application/gp_project/costs/show.html.erb
  config/locales/funding_application/gp_project/costs/cy.yml
  config/locales/funding_application/gp_project/costs/en.yml
Labels: enhancement, ruby

#587 Fixed locale references on check your answers view
  app/views/funding_application/gp_project/check_answers/_capital_work.html.erb
  app/views/funding_application/gp_project/check_answers/_cash_contributions.html.erb
  app/views/funding_application/gp_project/check_answers/_community_matters.html.erb
  app/views/funding_application/gp_project/check_answers/_costs.html.erb
  app/views/funding_application/gp_project/check_answers/_description.html.erb
  app/views/funding_application/gp_project/check_answers/_difference.html.erb
  app/views/funding_application/gp_project/check_answers/_end_date.html.erb
  config/locales/en.yml
Labels: bug, ruby

#586 Fixed references to common heading caption in application journey
  app/views/funding_application/gp_project/best_placed/show.html.erb
  app/views/funding_application/gp_project/outcomes/show.html.erb
Labels: bug, ruby

#585 Fixed hardcoded anchor tags on grant request view
  app/views/funding_application/gp_project/grant_request/show.html.erb
Labels: bug, ruby

#582 Added capture of funding application payload to database
  app/jobs/application_to_salesforce_job.rb
  db/migrate/20210303085530_add_submitted_payload_to_funding_applications.rb
  db/schema.rb
Labels: enhancement, ruby

#589 Added creation of Salesforce objects using Restforce
  app/controllers/pre_application/expression_of_interest/check_answers_controller.rb
  app/controllers/pre_application/expression_of_interest/submitted_controller.rb
  app/controllers/pre_application/project_enquiry/check_answers_controller.rb
  app/controllers/pre_application/project_enquiry/submitted_controller.rb
  app/helpers/pre_application_helper.rb
  app/jobs/pre_application_to_salesforce_job.rb
  db/migrate/20210303085531_add_sales_force_reference_for_contact.rb
  db/migrate/20210303085532_add_sales_force_reference_for_project_enquiry.rb
  db/migrate/20210303102649_add_sales_force_reference_for_expression_of_interest.rb
  db/schema.rb
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby

#584 Added organisation questions to pre-application journeys
  app/controllers/address_controller.rb
  app/controllers/pre_application/expression_of_interest/check_answers_controller.rb
  app/controllers/pre_application/expression_of_interest/previous_contact_name_controller.rb
  app/controllers/pre_application/expression_of_interest/start_controller.rb
  app/controllers/pre_application/org/mission_controller.rb
  app/controllers/pre_application/org/type_controller.rb
  app/controllers/pre_application/project_enquiry/check_answers_controller.rb
  app/controllers/pre_application/project_enquiry/previous_contact_name_controller.rb
  app/controllers/pre_application/project_enquiry/start_controller.rb
  app/helpers/organisation_helper.rb
  app/helpers/pre_application_helper.rb
  app/views/address/show.html.erb
  app/views/pre_application/expression_of_interest/check_answers/_organisation_address.html.erb
  app/views/pre_application/expression_of_interest/check_answers/_organisation_mission.html.erb
  app/views/pre_application/expression_of_interest/check_answers/_organisation_name.html.erb
  app/views/pre_application/expression_of_interest/check_answers/_organisation_type.html.erb
  app/views/pre_application/expression_of_interest/check_answers/show.html.erb
  app/views/pre_application/org/mission/show.html.erb
  app/views/pre_application/org/type/show.html.erb
  app/views/pre_application/project_enquiry/check_answers/_organisation_address.html.erb
  app/views/pre_application/project_enquiry/check_answers/_organisation_mission.html.erb
  app/views/pre_application/project_enquiry/check_answers/_organisation_name.html.erb
  app/views/pre_application/project_enquiry/check_answers/_organisation_type.html.erb
  app/views/pre_application/project_enquiry/check_answers/show.html.erb
  config/locales/pre_application/pa_expression_of_interest/check_answers/en.yml
  config/locales/pre_application/pa_project_enquiry/check_answers/en.yml
  config/routes.rb
Labels: enhancement, ruby

#592 Fixed reference to page heading abstraction on password reset view
  app/views/devise/passwords/edit.html.erb
Labels: bug, ruby

#591 Added capture of additional organisation mission types
  app/models/organisation.rb
  app/views/organisation/mission/show.html.erb
  app/views/pre_application/org/mission/show.html.erb
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby

#596 Updates costs hint text for content designers
  config/locales/funding_application/gp_project/grant_request/en.yml
Labels: content

#598 Fixed character encoding in locale file
  config/locales/funding_application/gp_project/grant_request/cy.yml
  config/locales/funding_application/gp_project/grant_request/en.yml
Labels: bug

#597 Minor bug fixes
  app/helpers/pre_application_helper.rb
  app/views/pre_application/expression_of_interest/working_title/show.html.erb
  app/views/pre_application/project_enquiry/working_title/show.html.erb
  config/locales/dashboard/en.yml
Labels: bug, ruby

#580 Bumped Rails to 6.1.3
  Gemfile
  Gemfile.lock
  app/controllers/funding_application/bank_details/confirm_controller.rb
  app/views/funding_application/bank_details/enter/show.html.erb
  app/views/funding_application/payment_requests/enter_bank_details/show.html.erb
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  bin/yarn
  config.ru
  config/boot.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults_6_1.rb
  config/initializers/permissions_policy.rb
  db/migrate/20210303102650_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20210303102651_create_active_storage_variant_records.active_storage.rb
  db/schema.rb
Labels: dependencies, ruby

#599 Fixed bugs in get_organisation_type_for_salesforce method
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#601 retrieve, store and use the eoi salesforce reference in the notify ma…
  app/helpers/pre_application_helper.rb
  app/mailers/notify_mailer.rb
  db/migrate/20210308083810_add_eoi_reference_to_pa_expressions_of_interest.rb
  db/schema.rb
  lib/apis/salesforce/salesforce_api.rb
Labels: bug, ruby

#600 2425 - Removes aria label from link for screen readers
  app/views/organisation/summary/show.html.erb
Labels: accessibility

#603 Added Email__c field to Restforce Contact upsert
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby

#604 Accessibility and markup fixes
  app/views/funding_application/gp_project/cash_contributions/show.html.erb
  app/views/funding_application/gp_project/evidence_of_support/show.html.erb
  app/views/funding_application/gp_project/volunteers/show.html.erb
  app/views/funding_application/payment_requests/add_item_of_spend/show.html.erb
  app/views/organisation/mission/show.html.erb
  app/views/user/details/show.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_project/cash_contributions/en.yml
  config/locales/funding_application/gp_project/costs/en.yml
  config/locales/funding_application/gp_project/non_cash_contributions/en.yml
  config/locales/funding_application/gp_project/volunteers/en.yml
Labels: accessibility, bug

#609 Fixed potential XSS security vulnerability in pre-application journey
  app/views/pre_application/expression_of_interest/check_answers/_organisation_address.html.erb
  app/views/pre_application/project_enquiry/check_answers/_organisation_address.html.erb
Labels: bug, ruby

#581 Bumped govuk-frontend from 3.10.2 to 3.11.0
  package.json
  yarn.lock
Labels: dependencies, tech debt

#606 Contact and Account duplicate checks
  app/helpers/pre_application_helper.rb
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby

#611 Fixes based on Rails deprecation warnings
  app/controllers/concerns/object_errors_logger.rb
  app/models/legal_signatory.rb
  app/views/funding_application/gp_project/dates/show.html.erb
  app/views/partials/_form_group_errors.html.erb
  app/views/partials/_summary_errors.html.erb
  app/views/user/details/show.html.erb
Labels: ruby, tech debt

#610 Added controller tests for EOI PreviousContactNameController
  spec/controllers/pre_application/expression_of_interest/previous_contact_name_controller_spec.rb
  spec/factories/pa_expression_of_interest.rb
  spec/factories/pre_applications.rb
Labels: ruby, tech debt, tests

#612 Abstracted content from organisation type page for internationalisation
  app/views/organisation/type/show.html.erb
  config/locales/organisation/type/en.yml
Labels: ruby, tech debt

#613 Abstracted content from organisation numbers page for internationalisation
  app/views/organisation/numbers/show.html.erb
  config/locales/organisation/numbers/en.yml
Labels: ruby, tech debt

#614 Abstracted content from organisation mission for internationalisation
  app/views/organisation/mission/show.html.erb
  config/locales/en.yml
  config/locales/organisation/mission/en.yml
Labels: ruby, tech debt

#615 Abstracted content from organisation summary for internationalisation
  app/views/organisation/summary/show.html.erb
  config/locales/organisation/summary/en.yml
Labels: ruby, tech debt

#616 Abstracted organisation type markup into partial
  app/views/organisation/type/show.html.erb
  app/views/partials/organisation/_type_question.html.erb
  app/views/pre_application/org/type/show.html.erb
Labels: ruby, tech debt

#617 Abstracted content from organisation signatories for internationalisation
  app/views/organisation/signatories/show.html.erb
  config/locales/organisation/signatories/en.yml
Labels: ruby, tech debt

#618 Added controller tests for EOI WhatProjectDoesController
  spec/controllers/pre_application/expression_of_interest/what_project_does_controller_spec.rb
Labels: ruby, tech debt, tests

#619 Added controller tests for EOI WorkingTitleController
  spec/controllers/pre_application/expression_of_interest/working_title_controller_spec.rb
Labels: ruby, tech debt, tests

#620 Added controller tests for EOI ProgrammeOutcomesController
  spec/controllers/pre_application/expression_of_interest/programme_outcomes_controller_spec.rb
Labels: ruby, tech debt, tests

#621 Added controller tests for EOI HeritageFocusController
  spec/controllers/pre_application/expression_of_interest/heritage_focus_controller_spec.rb
Labels: ruby, tech debt, tests

#622 Added controller tests for EOI ProjectReasonsController
  spec/controllers/pre_application/expression_of_interest/project_reasons_controller_spec.rb
Labels: ruby, tech debt, tests

#623 Added controller tests for EOI ProjectTimescalesController
  spec/controllers/pre_application/expression_of_interest/project_timescales_controller_spec.rb
Labels: ruby, tech debt, tests

#624 Added controller tests for EOI OverallCostController
  spec/controllers/pre_application/expression_of_interest/overall_cost_controller_spec.rb
Labels: ruby, tech debt, tests

#625 Added controller tests for EOI LikelySubmissionDescriptionController
  spec/controllers/pre_application/expression_of_interest/likely_submission_description_controller_spec.rb
Labels: ruby, tech debt, tests

#626 Added controller tests for EOI PotentialFundingAmountController
  spec/controllers/pre_application/expression_of_interest/potential_funding_amount_controller_spec.rb
Labels: ruby, tech debt, tests

#608 Ticket 2423
  app/views/address/address_results.html.erb
  app/views/address/postcode_lookup.html.erb
  app/views/address/show.html.erb
  app/views/dashboard/_funding_applications.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/funding_application/bank_details/confirm/show.html.erb
  app/views/funding_application/gp_project/cash_contributions/show.html.erb
  app/views/funding_application/gp_project/grant_request/show.html.erb
  app/views/funding_application/payment_requests/confirm_bank_details/show.html.erb
  app/views/pre_application/expression_of_interest/submitted/show.html.erb
  config/locales/devise/passwords/new/en.yml
  config/locales/en.yml
Labels: accessibility, enhancement

#628 Organisation details - Heading bug and accessibility fixes
  app/views/address/address_results.html.erb
  app/views/address/postcode_lookup.html.erb
  app/views/address/show.html.erb
Labels: accessibility, bug

#629 changes wording and uses endashes
  app/views/dashboard/_funding_applications.html.erb
  app/views/dashboard/_pa_expressions_of_interest.html.erb
  app/views/dashboard/_pa_project_enquiries.html.erb
  config/locales/en.yml
Labels: content

#627 Added controller tests for EOI StartController
  spec/controllers/pre_application/expression_of_interest/start_controller_spec.rb
Labels: ruby, tech debt, tests

#630 Added controller tests for EOI SubmittedController
  app/controllers/pre_application/expression_of_interest/submitted_controller.rb
  spec/controllers/pre_application/expression_of_interest/submitted_controller_spec.rb
Labels: ruby, tech debt, tests

#634 Added controller tests for EOI CheckAnswersController
  spec/controllers/pre_application/expression_of_interest/check_answers_controller_spec.rb
Labels: ruby, tech debt, tests

#635 Updated organisation feature tests to account for i18n
  spec/features/organisation_spec.rb
Labels: ruby, tech debt, tests

#636 Fixed issue where authenticate_user! is called twice
  app/controllers/concerns/payment_request_context.rb
  app/controllers/concerns/pre_application_context.rb
  app/controllers/pre_application/org/type_controller.rb
Labels: bug, ruby

#638 Fixed string interpolation bug in dashboard partials
  app/views/dashboard/_funding_applications.html.erb
  app/views/dashboard/_pa_expressions_of_interest.html.erb
  app/views/dashboard/_pa_project_enquiries.html.erb
Labels: bug, ruby

#637 Abstracted funding application project title markup into partial
  app/views/funding_application/gp_project/title/show.html.erb
  app/views/partials/funding_application/_title_question.html.erb
Labels: ruby, tech debt

#639 Abstracted funding application project description markup into partial
  app/views/funding_application/gp_project/description/show.html.erb
  app/views/partials/funding_application/_description_question.html.erb
Labels: ruby, tech debt

#633 Abstracted organisation signatories markup into partial
  app/views/organisation/signatories/show.html.erb
  app/views/partials/organisation/_signatories_question.html.erb
Labels: ruby, tech debt

#632 Abstracted organisation mission markup into partial
  app/views/organisation/mission/show.html.erb
  app/views/partials/organisation/_mission_question.html.erb
  app/views/pre_application/org/mission/show.html.erb
Labels: ruby, tech debt

#631 Abstracted organisation numbers markup into partial
  app/views/organisation/numbers/show.html.erb
  app/views/partials/organisation/_numbers_question.html.erb
Labels: ruby, tech debt

#640 Abstracted funding application project capital works into partial
  app/views/funding_application/gp_project/capital_works/show.html.erb
  app/views/partials/funding_application/_capital_works_question.html.erb
Labels: ruby, tech debt

#643 Abstracted funding application project location into partial
  app/views/funding_application/gp_project/location/show.html.erb
  app/views/partials/funding_application/_location_question.html.erb
Labels: ruby, tech debt

#644 Abstracted funding application project difference into partial
  app/views/funding_application/gp_project/difference/show.html.erb
  app/views/partials/funding_application/_difference_question.html.erb
  config/locales/funding_application/gp_project/difference/en.yml
Labels: ruby, tech debt

#645 Abstracted funding application project heritage into partial
  app/views/funding_application/gp_project/heritage/show.html.erb
  app/views/partials/funding_application/_heritage_question.html.erb
Labels: ruby, tech debt

#646 Abstracted funding application project matter into partial
  app/views/funding_application/gp_project/matter/show.html.erb
  app/views/partials/funding_application/_matter_question.html.erb
Labels: ruby, tech debt

#647 Abstrated funding application project best placed into partial
  app/views/funding_application/gp_project/best_placed/show.html.erb
  app/views/partials/funding_application/_best_placed_question.html.erb
Labels: ruby, tech debt

#648 Abstracted funding application project involvement into partial
  app/views/funding_application/gp_project/involvement/show.html.erb
  app/views/partials/funding_application/_involvement_question.html.erb
Labels: ruby, tech debt

#649 Abstracted funding application project outcomes into partial
  app/views/funding_application/gp_project/outcomes/show.html.erb
  app/views/partials/funding_application/_outcomes_question.html.erb
Labels: ruby, tech debt

#650 Abstracted funding application project dates into partial
  app/views/funding_application/gp_project/dates/show.html.erb
  app/views/partials/funding_application/_dates_question.html.erb
Labels: ruby, tech debt

#651 Abstracted funding application project permission into partial
  app/views/funding_application/gp_project/permission/show.html.erb
  app/views/partials/funding_application/_permission_question.html.erb
Labels: ruby, tech debt

#652 Abstracted funding application project accounts into partial
  app/views/funding_application/gp_project/accounts/show.html.erb
  app/views/funding_application/gp_project/accounts/show.js.erb
  app/views/partials/funding_application/_accounts_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_project/accounts/en.yml
Labels: ruby, tech debt

#656 Removed spurious full stop from cookie banner markup
  app/views/partials/_cookie_banner.html.erb
Labels: bug, content

#653 Abstracted funding application project governing docs into partial
  app/views/funding_application/gp_project/governing_documents/show.html.erb
  app/views/funding_application/gp_project/governing_documents/show.js.erb
  app/views/partials/funding_application/_governing_documents_question.html.erb
  config/locales/funding_application/gp_project/governing_document/en.yml
Labels: ruby, tech debt

#657 Fixed issue with removeFormGroupErrors on accounts view
  app/javascript/error-handling/index.js
  app/views/funding_application/gp_project/accounts/show.js.erb
  app/views/partials/funding_application/_accounts_question.html.erb
Labels: bug, javascript

#654 Abstracted funding application project volunteers into partial
  app/views/funding_application/gp_project/volunteers/show.html.erb
  app/views/partials/funding_application/volunteers/_page_upper.html.erb
  app/views/partials/funding_application/volunteers/_question.html.erb
  config/locales/funding_application/gp_project/volunteers/en.yml
Labels: ruby, tech debt

#655 Abstracted funding application project evidence into partial
  app/views/funding_application/gp_project/evidence_of_support/show.html.erb
  app/views/partials/funding_application/evidence_of_support/_page_upper.html.erb
  app/views/partials/funding_application/evidence_of_support/_question.html.erb
  config/locales/funding_application/gp_project/evidence_of_support/cy.yml
  config/locales/funding_application/gp_project/evidence_of_support/en.yml
Labels: ruby, tech debt

#658 Fixed issue with removeFormGroupErrors on governing docs view
  app/views/funding_application/gp_project/governing_documents/show.js.erb
  app/views/partials/funding_application/_governing_documents_question.html.erb
Labels: bug, javascript

#665 English changes for sign in page
  app/views/partials/_criteria_banner.html.erb
  config/locales/covid_banner/en.yml
  config/locales/devise/sessions/new/en.yml
Labels: accessibility, content

#666 Updated organisations data model to reflect medium grants questions
  db/migrate/20210324091348_update_organisations_data_model.rb
  db/schema.rb
Labels: enhancement, ruby

#659 Abstracted funding application project costs into partial
  app/views/funding_application/gp_project/costs/show.html.erb
  app/views/partials/funding_application/costs/_page_upper.html.erb
  app/views/partials/funding_application/costs/_question.html.erb
Labels: ruby, tech debt

#661 Abstracted funding application project non cash contributions
  app/views/funding_application/gp_project/non_cash_contributions/question.html.erb
  app/views/funding_application/gp_project/non_cash_contributions/show.html.erb
  app/views/partials/funding_application/non_cash_contributions/_add_question.html.erb
  app/views/partials/funding_application/non_cash_contributions/_generic_question.html.erb
  app/views/partials/funding_application/non_cash_contributions/_page_upper.html.erb
  config/locales/funding_application/gp_project/non_cash_contributions/cy.yml
  config/locales/funding_application/gp_project/non_cash_contributions/en.yml
Labels: ruby, tech debt

#660 Abstracted funding application project cash contributions into partial
  app/views/funding_application/gp_project/cash_contributions/question.html.erb
  app/views/funding_application/gp_project/cash_contributions/show.html.erb
  app/views/partials/funding_application/cash_contributions/_add_question.html.erb
  app/views/partials/funding_application/cash_contributions/_generic_question.html.erb
  app/views/partials/funding_application/cash_contributions/_page_upper.html.erb
Labels: ruby, tech debt

#662 Abstracted funding application project confirm declaration
  app/views/funding_application/gp_project/declaration/show_confirm_declaration.html.erb
  app/views/partials/funding_application/declaration/_confirm_question.html.erb
  config/locales/funding_application/gp_project/confirm_declaration/en.yml
Labels: ruby, tech debt

#667 updated cy.ymls
  config/locales/covid_banner/cy.yml
  config/locales/devise/sessions/new/cy.yml
Labels: accessibility, content

#663 Abstracted funding application project declaration into partial
  app/views/funding_application/gp_project/declaration/show_declaration.html.erb
  app/views/partials/funding_application/declaration/_question.html.erb
  config/locales/funding_application/gp_project/declaration/en.yml
Labels: ruby, tech debt

#668 Fixed issue with pre-application context before_action method
  app/controllers/concerns/pre_application_context.rb
Labels: bug, ruby

#669 Added initial page for medium grants funding application
  app/controllers/concerns/funding_application_context.rb
  app/controllers/dashboard_controller.rb
  app/controllers/funding_application/gp_open_medium/org/main_purpose_and_activities_controller.rb
  app/controllers/funding_application/gp_open_medium/start_controller.rb
  app/controllers/new_application_controller.rb
  app/models/application/common/funding_application.rb
  app/models/open_medium.rb
  app/models/organisation.rb
  app/models/user.rb
  app/views/dashboard/_funding_applications.html.erb
  app/views/funding_application/gp_open_medium/org/main_purpose_and_activities/show.html.erb
  app/views/funding_application/gp_open_medium/start/show.html.erb
  app/views/new_application/show.html.erb
  app/views/partials/organisation/_main_purpose_and_activities_question.html.erb
  config/initializers/flipper.rb
  config/locales/dashboard/en.yml
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/start/en.yml
  config/locales/new_application/en.yml
  config/locales/organisation/main_purpose_and_activities/en.yml
  config/routes.rb
  db/migrate/20210324095018_create_gp_open_medium_table.rb
  db/schema.rb
Labels: enhancement, ruby

#671 Fixed extra zero in dashboard content
  config/locales/en.yml
Labels: bug

#673 Added organisation vat number to medium grants journey
  app/controllers/funding_application/gp_open_medium/org/board_members_or_trustees_controller.rb
  app/controllers/funding_application/gp_open_medium/org/vat_registered_controller.rb
  app/models/organisation.rb
  app/views/funding_application/gp_open_medium/org/vat_registered/show.html.erb
  app/views/partials/organisation/_vat_registered_question.html.erb
  config/locales/en.yml
  config/locales/organisation/vat_registered/en.yml
  config/routes.rb
  db/seeds.rb
Labels: enhancement, ruby

#672 Added organisation social media section to medium grants journey
  app/controllers/funding_application/gp_open_medium/org/social_media_controller.rb
  app/models/organisation.rb
  app/views/funding_application/gp_open_medium/org/social_media/show.html.erb
  app/views/partials/organisation/_social_media_question.html.erb
  config/locales/en.yml
  config/locales/organisation/social_media/en.yml
  config/routes.rb
Labels: enhancement, ruby

#675 Added spend in the last financial year question
  app/controllers/funding_application/gp_open_medium/org/social_media_controller.rb
  app/controllers/funding_application/gp_open_medium/org/spend_last_year_controller.rb
  app/models/organisation.rb
  app/views/funding_application/gp_open_medium/org/spend_last_year/show.html.erb
  app/views/partials/organisation/_spend_last_year_question.html.erb
  config/locales/en.yml
  config/locales/organisation/spend_last_year/en.yml
  config/routes.rb
Labels: enhancement, ruby

#674 Added unrestricted funds question to medium grants journey
  app/controllers/funding_application/gp_open_medium/org/unrestricted_funds_controller.rb
  app/models/organisation.rb
  app/views/funding_application/gp_open_medium/org/unrestricted_funds/show.html.erb
  app/views/partials/organisation/_unrestricted_funds_question.html.erb
  config/locales/en.yml
  config/locales/organisation/unrestricted_funds/en.yml
  config/routes.rb
Labels: enhancement, ruby

#676 Added project advice question to medium grants application
  app/controllers/funding_application/gp_open_medium/received_advice_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/received_advice/show.html.erb
  app/views/partials/funding_application/_received_advice_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/received_advice/en.yml
  config/routes.rb
Labels: enhancement, ruby

#677 Added project title question to medium grants journey
  app/controllers/funding_application/gp_open_medium/title_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/title/show.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: enhancement, ruby

#678 Added first application question to medium grants journey
  app/controllers/funding_application/gp_open_medium/first_fund_application_controller.rb
  app/controllers/funding_application/gp_open_medium/org/unrestricted_funds_controller.rb
  app/controllers/funding_application/gp_open_medium/received_advice_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/first_fund_application/show.html.erb
  app/views/partials/_summary_errors.html.erb
  app/views/partials/funding_application/_first_fund_application_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/first_fund_application/en.yml
  config/routes.rb
Labels: enhancement, ruby

#679 Added why now question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/dates_controller.rb
  app/controllers/funding_application/gp_open_medium/why_now_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/why_now/show.html.erb
  app/views/partials/funding_application/_why_now_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/why_now/en.yml
  config/routes.rb
Labels: enhancement, ruby

#680 Added location question to open medium grant journey
  app/controllers/address_controller.rb
  app/controllers/funding_application/gp_open_medium/location_controller.rb
  app/models/open_medium.rb
  app/views/address/address_results.html.erb
  app/views/address/postcode_lookup.html.erb
  app/views/address/show.html.erb
  app/views/funding_application/gp_open_medium/location/show.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: enhancement, ruby

#685 Added heritage at risk question to medium grant journey
  app/controllers/funding_application/gp_open_medium/at_risk_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/at_risk/show.html.erb
  app/views/partials/funding_application/_at_risk_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/at_risk/en.yml
  config/routes.rb
Labels: enhancement, ruby

#686 Added visitors question to medium grants journey
  app/controllers/funding_application/gp_open_medium/visitors_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/visitors/show.html.erb
  app/views/partials/funding_application/_visitors_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/visitors/en.yml
  config/routes.rb
Labels: enhancement, ruby

#688 Added environmental impacts question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/environmental_impacts_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/environmental_impacts/show.html.erb
  app/views/partials/funding_application/_environmental_impacts_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/environmental_impacts/en.yml
  config/routes.rb
Labels: enhancement, ruby

#689 Added best placed description question to open medium journey
  app/controllers/funding_application/gp_open_medium/best_placed_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/best_placed/show.html.erb
  app/views/funding_application/gp_project/best_placed/show.html.erb
  app/views/partials/funding_application/_best_placed_question.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: enhancement, ruby

#695 Added project management question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/managed_controller.rb
  app/javascript/error-handling/index.js
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/managed/show.html.erb
  app/views/funding_application/gp_open_medium/managed/show.js.erb
  app/views/partials/funding_application/_managed_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/managed/en.yml
  config/routes.rb
Labels: enhancement, ruby

#696 Added jobs question to open medium grant journey
  app/controllers/funding_application/gp_open_medium/jobs_controller.rb
  app/javascript/error-handling/index.js
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/jobs/show.html.erb
  app/views/funding_application/gp_open_medium/jobs/show.js.erb
  app/views/partials/funding_application/_jobs_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/jobs/en.yml
  config/routes.rb
Labels: enhancement, ruby

#699 Feature/stub missing pages
  app/controllers/funding_application/gp_open_medium/acknowledgement_description_controller.rb
  app/controllers/funding_application/gp_open_medium/at_risk_controller.rb
  app/controllers/funding_application/gp_open_medium/best_placed_controller.rb
  app/controllers/funding_application/gp_open_medium/capital_works_controller.rb
  app/controllers/funding_application/gp_open_medium/cash_contributions_controller.rb
  app/controllers/funding_application/gp_open_medium/costs_controller.rb
  app/controllers/funding_application/gp_open_medium/difference_controller.rb
  app/controllers/funding_application/gp_open_medium/evaluation_description_controller.rb
  app/controllers/funding_application/gp_open_medium/evidence_of_support_controller.rb
  app/controllers/funding_application/gp_open_medium/heritage_formal_designation_description_controller.rb
  app/controllers/funding_application/gp_open_medium/is_partnership_controller.rb
  app/controllers/funding_application/gp_open_medium/non_cash_contributions_controller.rb
  app/controllers/funding_application/gp_open_medium/outcomes_controller.rb
  app/controllers/funding_application/gp_open_medium/permission_controller.rb
  app/controllers/funding_application/gp_open_medium/volunteers_controller.rb
  app/models/open_medium.rb
  app/views/funding_application/gp_open_medium/acknowledgement_description/show.html.erb
  app/views/funding_application/gp_open_medium/capital_works/show.html.erb
  app/views/funding_application/gp_open_medium/cash_contributions/show.html.erb
  app/views/funding_application/gp_open_medium/costs/show.html.erb
  app/views/funding_application/gp_open_medium/evidence_of_support/show.html.erb
  app/views/funding_application/gp_open_medium/heritage_formal_designation_description/show.html.erb
  app/views/funding_application/gp_open_medium/is_partnership/show.html.erb
  app/views/funding_application/gp_open_medium/jobs/show.html.erb
  app/views/funding_application/gp_open_medium/non_cash_contributions/show.html.erb
  app/views/funding_application/gp_open_medium/volunteers/show.html.erb
  app/views/partials/funding_application/_acknowledgement_description_question.html.erb
  config/locales/en.yml
  config/locales/funding_application/gp_open_medium/acknowledgement_description/en.yml
  config/routes.rb
Labels: enhancement, ruby
