Repository heritagefund/funding-frontend, pull requests merged in 2021-01, with the labels that each got.

#505 Bump node-notifier from 7.0.2 to 8.0.1
  yarn.lock
Labels: dependencies

#506 Updated govuk-frontend from 3.10.1 to 3.10.2
  package.json
  yarn.lock
Labels: dependencies

#503 Updated confirm payment details page content
  app/views/funding_application/gp_project/payment_details/show.html.erb
  config/locales/funding_application/gp_project/payment_confirm_details/en.yml
  config/locales/funding_application/gp_project/payment_details/en.yml
Labels: content, enhancement

#507 Added NotifyMailer methods for PEF and EOI confirmation emails
  app/mailers/notify_mailer.rb
Labels: enhancement, ruby

#508 Added an additional organisation type to the org_type enum
  app/models/organisation.rb
  app/models/project.rb
  app/views/organisation/type/show.html.erb
Labels: enhancement, ruby

#517 Added missing service to manifest-research.yml
  manifest-research.yml
Labels: ci/cd

#516 Updated PreApplicationContext to fix additional access case
  app/controllers/concerns/pre_application_context.rb
Labels: bug, ruby

#510 Run CI pipeline only on PRs instead of every commit
  .github/workflows/continuous-integration-workflow.yml
Labels: ci/cd

#520 Fixed a file upload field bug present in Firefox
  app/controllers/funding_application/gp_project/accounts_controller.rb
  app/views/funding_application/gp_project/accounts/show.html.erb
  app/views/funding_application/gp_project/capital_works/show.html.erb
  app/views/funding_application/gp_project/cash_contributions/show.html.erb
  app/views/funding_application/gp_project/evidence_of_support/show.html.erb
  app/views/funding_application/gp_project/governing_documents/show.html.erb
  app/views/funding_application/gp_project/payment_confirm_details/show.html.erb
Labels: bug, ruby

#521 Added a GitHub Action to trigger research environment deployments
  .github/workflows/deploy-to-research-workflow.yml
Labels: ci/cd

#522 Added flipper_gates population to seeds.rb file
  README.md
  db/seeds.rb
Labels: ruby, tech debt

#530 best_placed string abstraction complete
  app/views/funding_application/gp_project/best_placed/show.html.erb
  config/locales/funding_application/gp_project/best_placed/en.yml
Labels: ruby, tech debt

#531 Fixed aria-describedby issue on funding app project title view
  app/views/funding_application/gp_project/title/show.html.erb
Labels: accessibility, bug

#533 Added database migration for additional user details
  db/migrate/20210121080143_add_additional_user_details.rb
  db/schema.rb
Labels: enhancement, ruby

#534 Added capture of additional details to user page
  app/controllers/user/details_controller.rb
  app/models/user.rb
  app/views/user/details/show.html.erb
  config/locales/en.yml
  config/locales/user/details/show/en.yml
Labels: enhancement, ruby

#535 Update pre-application journeys to capture user preferences
  app/controllers/pre_application/expression_of_interest/submitted_controller.rb
  app/controllers/pre_application/project_enquiry/submitted_controller.rb
  app/views/pre_application/expression_of_interest/submitted/show.html.erb
  app/views/pre_application/project_enquiry/submitted/show.html.erb
  config/locales/pre_application/pa_expression_of_interest/submitted/en.yml
  config/locales/pre_application/pa_project_enquiry/submitted/en.yml
  config/routes.rb
Labels: enhancement, ruby

#536 Added submission of pre-application payload functionality
  app/controllers/pre_application/expression_of_interest/check_answers_controller.rb
  app/controllers/pre_application/project_enquiry/check_answers_controller.rb
  app/jobs/pre_application_to_salesforce_job.rb
  app/mailers/notify_mailer.rb
  app/models/pre_application/pre_application.rb
  app/models/pre_application/pre_application_dclrtn.rb
  db/migrate/20210122083346_add_submitted_payload_to_pre_applications.rb
  db/schema.rb
Labels: enhancement, ruby

#537 Abstracted phase banner content into locale file
  app/views/partials/_phase-banner.html.erb
  config/locales/partials/phase_banner/en.yml
Labels: ruby, tech debt
