Repository heritagefund/funding-frontend, pull requests merged in 2021-05, with the labels that each got.

#757 Bumped Rails to v6.1.3.1
  Gemfile
  Gemfile.lock
Labels: dependencies

#762 Updated Rails from v6.1.3.1 to v6.1.3.2
  Gemfile
  Gemfile.lock
Labels: dependencies

#763 Fixed payment requests flow for medium grants
  app/controllers/concerns/funding_application_context.rb
  app/helpers/payment_details_and_request_helper.rb
Labels: bug, ruby

#767 Feature/payments journey
  app/assets/stylesheets/components/_list.scss
  app/controllers/concerns/funding_application_context.rb
  app/controllers/dashboard_controller.rb
  app/controllers/funding_application/bank_details/start_controller.rb
  app/controllers/funding_application/payment_requests/start_controller.rb
  app/controllers/funding_application/tasks_controller.rb
  app/helpers/application_helper.rb
  app/helpers/dashboard_helper.rb
  app/helpers/payment_details_and_request_helper.rb
  app/models/payment_request.rb
  app/views/dashboard/_awarded_projects.html.erb
  app/views/dashboard/_awarded_projects_tags.html.erb
  app/views/dashboard/_funding_applications.html.erb
  app/views/dashboard/_funding_applications_tags.html.erb
  app/views/dashboard/_pa_expressions_of_interest.html.erb
  app/views/dashboard/_pa_project_enquiries.html.erb
  app/views/dashboard/_pre_applications_tags.html.erb
  app/views/dashboard/show.html.erb
  app/views/funding_application/bank_details/start/show.html.erb
  app/views/funding_application/payment_requests/confirm_bank_details/show.html.erb
  app/views/funding_application/payment_requests/enter_bank_details/show.html.erb
  app/views/funding_application/payment_requests/start/show.html.erb
  app/views/funding_application/payment_requests/submitted/show.html.erb
  app/views/funding_application/tasks/show.html.erb
  app/views/partials/_summary_errors.html.erb
  app/views/partials/_tag_component.html.erb
  config/locales/cy.yml
  config/locales/dashboard/cy.yml
  config/locales/dashboard/en.yml
  config/locales/en.yml
  config/locales/funding_application/payment_confirm_details/cy.yml
  config/locales/funding_application/payment_confirm_details/en.yml
  config/locales/funding_application/payment_details/cy.yml
  config/locales/funding_application/payment_details/en.yml
  config/locales/funding_application/payment_details_submitted/cy.yml
  config/locales/funding_application/payment_details_submitted/en.yml
  config/locales/funding_application/payment_requests/start_payment/cy.yml
  config/locales/funding_application/payment_requests/start_payment/en.yml
  config/locales/funding_application/payment_requests/tasks/cy.yml
  config/locales/funding_application/payment_requests/tasks/en.yml
  config/routes.rb
  db/migrate/20210518150411_add_submitted_on_to_payment_requests.rb
  db/schema.rb
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby

#764 Updated govuk-frontend from v3.11.0 to v3.12.0
  package.json
  yarn.lock
Labels: dependencies

#769 Updated criteria banner content
  config/locales/covid_banner/cy.yml
  config/locales/covid_banner/en.yml
Labels: content

#771 updated payments journey to look at correct SF field and added an email sent at the time that bank details are submitted
  app/controllers/dashboard_controller.rb
  app/helpers/dashboard_helper.rb
  app/helpers/payment_details_and_request_helper.rb
  app/mailers/notify_mailer.rb
  app/views/dashboard/_awarded_projects.html.erb
  lib/apis/salesforce/salesforce_api.rb
Labels: enhancement, ruby
